version: "3"

services:
  backend:
    build:
      context: ./demo-spring
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./demo-angular
    ports:
      - "8081:8081"
    depends_on:
      - backend
